# basic option. i can say whatever here.
title: Vibhs Notes
author:
  name: "Vibhanshu Mitra"
  email: "vibh@gmail.com"
description: A lovely wonderful site.
twitter_username: vibhmitra
github_username: vibhmitra

# build settings
markdown: kramdown
theme: minima
