# site settings
title: Vibhs Notes
author:
  name: "Vibhanshu Mitra"
  email: "vibh@gmail.com"
description: A lovely wonderful site.
twitter_username: vibhmitra
github_username: vibhmitra

# build settings
markdown: kramdown
remote_theme: jekyll/minima
