# site settings
title: Vibhs Notes
author:
  name: "Vibhanshu Mitra"
  email: "vibhanshumitra@gmail.com"
description: Well, Just a test site.
twitter_username: vibhmitra
github_username: vibhmitra

# build settings
markdown: kramdown
remote_theme: jekyll/minima
